### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by petr-tik** [condnsdmatters/smithers#1]
A game of poker is effectively run by having the bots listening on web sockets (or raw sockets), and being sent (publically) 

should be:

A game of poker is effectively run by having the bots listening on web sockets (or raw sockets), and being sent (**publicly**)

**Comment by condnsdmatters** [comment]
Thanks petr. I dont think thats the only typo in the readme, and it probably wont be the last I make, but I'll correct it next time I update the README... Thanks for your attentiveness!

**Comment by condnsdmatters** [comment]
the correction to this issue is now publicly visible
